service: employee-management

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1 # Change to your desired AWS region
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
      Resource: "arn:aws:dynamodb:us-east-1:your-account-id:table/EmployeeTable" # Replace with your DynamoDB table ARN

functions:
  createEmployee:
    handler: handler.handler
    events:
      - http:
          path: create-employee
          method: post

resources:
  Resources:
    EmployeeTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: EmployeeTable
        AttributeDefinitions:
          - AttributeName: employeeId
            AttributeType: S
        KeySchema:
          - AttributeName: employeeId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5 # Adjust based on your needs
